# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-24 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20170524_2306'),
    ]

    operations = [
        migrations.AddField(
            model_name='election',
            name='open_now',
            field=models.BooleanField(default=True),
        ),
    ]
