# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 22:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20170525_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='open_now',
        ),
    ]
